name: Test Telegram Message

on:
  workflow_dispatch: # 手动触发

jobs:
  test-message:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run bot script
      env:
        FINNHUB_API_KEY: ${{ secrets.FINNHUB_API_KEY }}
        DEBUG_MODE: ${{ secrets.DEBUG_MODE }}
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        CHAT_ID: ${{ secrets.CHAT_ID }}
        LLM_API_TOKEN: ${{ secrets.LLM_API_TOKEN }}
      run: python src/main.py
